module.exports = {
  ok: "success",
  userRegister: "Your Request Has Been sent for Approval",
  QuoteAdded: "Quote added successfully",
  NotFound: "Record Not Found",
  NotApproved: "Your Account Has Not Been Approved Till Yet",
  emailAlreadyExist: "Record Already Exist",
  updateSuccess: "Updated successfully",
  deleteSuccess: "Deleted successfully",
  incorrectPassword: "Incorrect Email or Password",
  incorrectOldPassword: "Your password is incorrect",
  passwordUpdate: "Password update successfull",
  emailSent: "Mail has been sent",
  serverError: "Internal Server Error",
  validationErrors: "Validation Errors",
  empytyField: "Please Enter",
  chargeMethod: "Charge Method is not created",
  RefundCreated: "Refund Generated",
  RefundNotGenrated: "Refund Not Genrated",
  PaymentIntentCreated: "Request Created Successfully",
  paymentUpdate: "Payment Not Updated",
  paymentCapture: "Payment Not Captured",
  paymentConfirm: "Payment Charged",
  paymentRecord: "payment record not created",
  wrongAmount: "Please Enter Correct Amount",
  unPaidPayments: "All UnPaid Payments Details",
  paymentStatusNotUpdated: "Your Payment Status Not Updated",
  paymentStatusUpdated: "Your Payment Status Updated",
  success: "Payment Paid Successfully",
  cancelPaymentIntent: "payment Intent Cancelled",
  pendingQuotes: "No Pending Quotes",
  pendingQuotesDetails: "All Pending Quotes Details",
  statusApproved: "Approved Quote Successfully",
  statusCancelled: "Cancelled Quote Successfully",
};
